name: flutter_plugin_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.9
author: Tiago Ribeiro <tiagopribeiro.1992@gmail.com>
homepage: https://github.com/CrossPT/flutter_plugin_pdf_viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  effective_dart: ^1.2.1
  flutter_cache_manager: ^3.1.2
  path_provider: ^2.0.3
  rxdart: ^0.27.2
  numberpicker: ^1.2.1
  photo_view: ^0.10.2

flutter:
  plugin:
    androidPackage: pt.tribeiro.flutter_plugin_pdf_viewer
    pluginClass: FlutterPluginPdfViewerPlugin
